### ISSUE TITLE
using the embed_conv instead of patch_embed

### ISSUE THREAD

**Issue by zhou-rui1** [OliverRensu/co-advise#1]
https://github.com/OliverRensu/co-advise/blob/8049918d059caa90a69ce5791d906117ea2af453/models.py#L54
Hi, it seems that if the embed_conv is used, the ViT model archiecture will change, other than just ditilling the cls tokens, as presented in the paper?

**Comment by OliverRensu** [comment]
Hi, Table 3 reports 2 kinds of settings: 1)  CiT-S keeps the same
architecture and achieves 82.0% 2) CiT-SAK has token inductive bias
Alignment and achieves 82.7%. You can replace the  embed_conv by
non-overlap patch embedding for  CiT-S.

rachel ***@***.***> 于2022年11月12日周六 23:22写道：

**Comment by zhou-rui1** [comment]
Thanks for reply.
